title: Mehdi Mashayekhi blog
name: "Mehdi's Tech Blog"
author: Mehdi Mashayekhi
twitter_username: Medi_Mashayekhi
baseurl: "/mehdi-mashayekhi-blog.github.io"
description: Document my learning notes.
profile_url: "https://mehdimashayekhi.github.io/mehdi-mashayekhi-blog.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
